apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /ws
  name: ingress-c8490260
spec:
  rules:
    - host: hello-world.info
      http:
        paths:
          - backend:
              service:
                name: bot-2499-290a7a4
                port:
                  number: 80
            path: /bots/bot-2499-290a7a4
            pathType: Prefix
          - backend:
              service:
                name: bot-2499-f3942ee
                port:
                  number: 80
            path: /bots/bot-2499-f3942ee
            pathType: Prefix
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-account-c8da9ab8
