apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: ingress-c8490260
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: test
                port:
                  number: 3000
            path: /bots/test
            pathType: Prefix
    - http:
        paths:
          - backend:
              service:
                name: testyeet
                port:
                  number: 3000
            path: /bots/testyeet
            pathType: Prefix
