apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /ws
  name: ingress-c8490260
spec:
  rules:
    - host: hello-world.info
      http:
        paths:
          - backend:
              service:
                name: tmp
                port:
                  number: 80
            path: /tmp
            pathType: Prefix
